### ISSUE TITLE
[Feature]: Integrate a simple OrbitDB command to your CLI

### ISSUE THREAD

**Issue by RezaRahemtola** [PoCInnovation/orbit-db-cli#7]
### Description

Use OrbitDB locally in your CLI :rocket: 

### Expected behaviour

Here's what you have to do:
- [x] Select a database for your first feature between the [log](https://github.com/orbitdb/orbit-db/blob/main/API.md#orbitdblognameaddress), [feed](https://github.com/orbitdb/orbit-db/blob/main/API.md#orbitdbfeednameaddress) and [key-value](https://github.com/orbitdb/orbit-db/blob/main/API.md#orbitdbkeyvaluenameaddress)
- [x] Look at the [code of the current CLI](https://github.com/orbitdb/orbit-db-cli/tree/main/src) to develop your own command logic
- [x] Create a schema / notion page in your workspace explaining how you will store the data linked to this database.
> You can look at [the way the orbit-db-cli handles it](https://github.com/orbitdb/orbit-db-cli#data-directories-and-paths) :wink: 
- [x] Implement basics commands to your CLI to add an element to the DB and retrieve it

### Environment

/

**Comment by Saverio976** [comment]
I think we can close this right ?
